# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('full_name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('valued_goals', models.TextField(blank=True)),
                ('self_enquiry', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OACatalog',
            fields=[
                ('catalogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leafv1.CatalogEntry')),
                ('description', models.TextField(blank=True, null=True)),
                ('ro_number', models.CharField(max_length=5, null=True)),
            ],
            bases=('leafv1.catalogentry',),
        ),
        migrations.CreateModel(
            name='OARecord',
            fields=[
                ('dailyrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leafv1.DailyRecord')),
                ('comments', models.TextField(blank=True)),
                ('catalog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leafv1.OACatalog')),
            ],
            bases=('leafv1.dailyrecord',),
        ),
        migrations.CreateModel(
            name='TFCatalog',
            fields=[
                ('catalogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leafv1.CatalogEntry')),
            ],
            bases=('leafv1.catalogentry',),
        ),
        migrations.CreateModel(
            name='TFRecord',
            fields=[
                ('dailyrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leafv1.DailyRecord')),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('catalog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leafv1.TFCatalog')),
            ],
            bases=('leafv1.dailyrecord',),
        ),
        migrations.AddField(
            model_name='weekrecord',
            name='oa_entries',
            field=models.ManyToManyField(to='leafv1.OACatalog'),
        ),
        migrations.AddField(
            model_name='weekrecord',
            name='tf_entries',
            field=models.ManyToManyField(to='leafv1.TFCatalog'),
        ),
    ]
