# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leafv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oacatalog',
            name='ro_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='weekrecord',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weekrecord',
            name='start_date',
            field=models.DateField(),
        ),
    ]
